gocolly/colly

- colly.go
> Adding support to pass a custom http.Transport

- examples/basic/basic.go
- examples/coursera_courses/coursera_courses.go
- examples/max_depth/max_depth.go
- examples/parallel/parallel.go
- examples/rate_limit/rate_limit.go
- examples/request_context/request_context.go
Add comments to example scrapers.
> add comments to examples

- colly.go
Hi,
my crawled stated to crawl some social media pages, which are linked on almost every page, so I thought that it would be nice if I can add list of domains which I don't want to crawl.
> handling of DisallowedDomains

- colly.go
- colly_test.go
I've added logic to pull and cache robots.txt files for each host the crawler reaches.  Each request verifies the URL against the host's robots.txt file.  This adds a dependency on the https://github.com/temoto/robotstxt project.
A new flag was also added to the `Collector` in order to `IgnoreRobotsTxt`.  Setting this to `true` skips the robots.txt validation.
> Robots.txt

- colly.go
- replace strings.Index with strings.Contains
- drop zero in map initialization
> [enc] simplification

- colly.go
- colly_test.go
> Implement OnScraped callback

- context.go
- context_test.go
> Add iteration api for context

- colly.go
- colly_test.go
Issue https://github.com/gocolly/colly/issues/80
> Add functional options for NewCollector

- colly_test.go
* remove unnecessary types
*  break down `TestNewCollector` into smaller functions
> minor style fixes to satisfy goreportcard

- .travis.yml
- _examples/basic/basic.go
- _examples/coursera_courses/coursera_courses.go
- _examples/google_groups/google_groups.go
- _examples/hackernews_comments/hackernews_comments.go
- _examples/instagram/instagram.go
- _examples/max_depth/max_depth.go
- _examples/multipart/multipart.go
- _examples/openedx_courses/openedx_courses.go
- _examples/parallel/parallel.go
- _examples/proxy_switcher/proxy_switcher.go
- _examples/random_delay/random_delay.go
- _examples/rate_limit/rate_limit.go
- _examples/url_filter/url_filter.go
- _examples/xkcd_store/xkcd_store.go
Use functional options for NewCollector in examples
> Examples with functional options

- colly_test.go
Related to https://github.com/gocolly/colly/issues/83
> Use *httptest.Server in tests, remove init func

- htmlelement.go
Hi! There was some code left over from an example, I presume.
> corrected typo

- xmlelement.go
@asciimoo might require more checks and tests as html case is not covered
> fix ChildText panic if xpath does not exist in xml

- unmarshal.go
> Add support to field unmarshal ignore specification

- README.md
> Adding goquotes to the list of projects using colly

- _examples/instagram/instagram.go
The js file which contains the queryId for next page has changed.
There is 3 queryIds in the code, the first one is for saved posts, the second - the needed one - is for the next page.
> [fix] instagram example scraper fixed

- _examples/proxy_switcher/proxy_switcher.go
- colly.go
- proxy/proxy.go
- request.go
- Add ProxyURL to Request
- Add ProxyURL via context
- Update example
Addresses #110
> Proxy URL for request

- htmlelement.go
The counter does not get incremented at all at the moment
> Increment i before return True

- colly.go
- colly_test.go
> Fix checkRobots ignoring query parameters

- colly.go
> SetCookieJar input variable as interface instead strict type

- _examples/cryptocoinmarketcap/cryptocoinmarketcap.go
**Fix missing 1h,24h,7d values in the csv file.**
(Existing code in repo is not able to retrieve those values).
> Update attr selectors to match current DOM

- colly.go
- colly_test.go
- request.go
Hi. First of all thanks for putting this great package together. It is amazing. I found myself in the need of having the ability to check if a URL had already been visited without having to call Visit() and as such created this PR. Please let me know your thoughts and best regards.
> adding ability to check if a URL has been visited.

- README.md
Added a new open source project using colly
> Update README.md with new project

- http_backend.go
> Fix LimitRule.DomainGlob typo

- extensions/random_user_agent.go
adds mobile user-agent generation
adds some comments and generated examples or user-agents
adds more Firefox and Chrome versions
> adds mobile useragents generation ++

- colly.go
> SetRedirectHandler bugfix (breaking changes)

- colly.go
So we can use http client and cookie jar across collectors and outside collector
> Add SetClient to set custom http client

- colly.go
- request.go
> add depth for Marshal

- colly.go
- colly_test.go
Previously, these checks were left outside the `requestCheck` function, and run after it.
Since the `requestCheck` has a side effect of marking URL as visited, URLs filtered out by DisallowedDomains blacklist or robots.txt would return `ErrForbiddenDomain`/`ErrRobotsTxtBlocked` on first visit attempt, but `ErrAlreadyVisited` on subsequent revisit attempts, which is inconsistent with behaviour of other checks.
> Move isDomainAllowed and robots.txt checks inside requestCheck

- colly.go
- colly_test.go
- http_backend.go
The callback is called just before reading the response body, and can be used to abort the request.
Closes #228.
> Add OnResponseHeaders callback

- colly.go
- colly_test.go
CollectorOption add CheckHead method
> Collector option add check head method

- _examples/parallel/parallel.go
- _examples/random_delay/random_delay.go
- _examples/rate_limit/rate_limit.go
- _examples/reddit/reddit.go
- colly.go
- colly_test.go
CollectorOption Async method delete parameter
> Async delete parameter

- README.md
> [update] add project to README.md

- _examples/reddit/reddit.go
reddit example throws error : _not enough arguments in call to colly.Async_
Fixed this by changing `colly.Async() `-> `colly.Async(true)`
Added an optional comment.
> Updated reddit example with correct arguments for calling colly.Async

- README.md
A scraper for movie sites that bypasses ads to return download links
> Added new project that uses Colly

- _examples/cryptocoinmarketcap/cryptocoinmarketcap.go
Hi Team,
First of all, thanks so much for putting together this amazing colly tool which is now a goto tool when dealing with web crawling problems.
I've been following the provided examples to explore more about colly and find the cryptocoinmarketcap example seems to be outdated. Hence provide this PR to update.
Cheer,s
Kewei
> update outdated cryptocoinmarketcap example

- README.md
let me know if you need any other information about the project or if you need more details about the Colly package use
> adding docker-slim to the list of open source projects using Colly

- _examples/coursera_courses/coursera_courses.go
Could you consider updating this example?
Seems like Coursera updated their website. This example was returning an empty list as the final result.
Changes:
- Update querySelectors
- save output to json file
> update coursera example

- queue/queue.go
> feat: support Stop() in queue

- colly.go
> Fix invalid base URL assignment

- colly.go
Signed-off-by: shubham <shubham.bajpai@mayadata.io>
This PR addresses the issue #543
> Fix race on count fields of Collector type

- README.md
> add quote crawler using colly

- colly.go
fix: CollectorOption Async useless parameter
> Fix Async ignoring its arguments

- colly.go
- colly_test.go
The url filters and disallowed url filters were not applied to the requests, which were redirected. I fixed it with this pr + added a test for it too. Let me know what you think about it.
> moving filterings to one function (checkFilters) and use it in case of redirect too

- colly.go
There are several commits, which are largely independent, but they touch the same code, so I thought it would be better to batch them together into single pull request instead of doing 2 extra rebases. Of course, if some of them are more questionable than others, I can split them to separate PRs. Please see the commit messages themselves for the description of what and why I attempted to do.
> Code cleanup

- colly.go
- colly_test.go
Some websites set a session cookie, and return a redirect to the same page instead of returning a response.
To illustrate this problem, this is how HTTP session might look like:
GET / HTTP/1.1
Host: 127.0.0.1:34931
User-Agent: colly - https://github.com/gocolly/colly/v2
Accept: */*
Accept-Encoding: gzip
HTTP/1.1 302 Found
Content-Type: text/html; charset=utf-8
Location: /
Set-Cookie: session_id=1
Date: Mon, 10 Apr 2023 23:29:29 GMT
Content-Length: 24
<a href="/">Found</a>.
GET / HTTP/1.1
Host: 127.0.0.1:34931
User-Agent: colly - https://github.com/gocolly/colly/v2
Accept: */*
Cookie: session_id=1
Referer: http://127.0.0.1:34931/
Accept-Encoding: gzip
HTTP/1.1 200 OK
Date: Mon, 10 Apr 2023 23:29:29 GMT
Content-Length: 12
Content-Type: text/plain; charset=utf-8
hello world
This fixes …
> Support websites redirecting to the same page when AllowURLRevisit is disabled

- README.md
Scrapper is someone who likes to fight. Scraper scrapes information.
> scrapper -> scraper Update README.md

- colly.go
> Add headers/ua to robots.txt request

- colly.go
- colly_test.go
- http_backend.go
https://github.com/gocolly/colly/issues/856
> add requestHeadersCallbacks to check request  after limit wait but before request 
