gocolly/colly

- colly.go
- http_backend.go
Hello!
This PR adds a default timeout to the http.Client (since a timeout of 0 is == no timeout in go) and adds collector.SetClientTimeout() to override it[1]. Also added a check on err after client.Do since it can cause a panic later on if the request fails.
[1]:
example: `c.SetClientTimeout(5 * time.Second)`
> Timeout for http.Client and bug fix

- colly.go
In `func (c *Collector) scrape`, `requestData` does not copy to `form`.
Because `form` is declared again at 192th line and it has a different scope with `form` at 190th line.
As a result, POST request always send no data.
> Fix POST request

- colly.go
- http_backend.go
I added some basic caching support. Changes should be backward compatible and enable cache only when `CacheDir` is defined. I needed to make `ContextMap` public to make request object serializable with gob.
> Caching when CacheDir is defined

- colly.go
does not RUnlock() when Ctx get the value
> does not RUnlock() when Ctx get the value

- colly.go
- http_backend.go
Apparently headers does not survive a redirect in net/http (https://github.com/golang/go/issues/4800) so here's a fix for that. Probably not the most elegant way of doing it though
> Copy the headers from the last request on redirect

- examples/openedx_courses/openedx_courses.go
This is example to scrape open edx courses data.
Platform info: 
- [Platform homepage ](https://open.edx.org)
- [Site Powered by Open edX](https://openedx.atlassian.net/wiki/spaces/COMM/pages/162245773/Sites+powered+by+Open+edX)
> [ENH] add open edx course scrapper example

- colly.go
- colly_test.go
Case scenario: Using HTMLElement in external package unittest
Problem: HTMLElement has local `attributes` that make impossible from other packages to instantiate a HTMLElement with values in attributes.
FIx: Implementation of NewHTMLElementFromSelectionNode
> NewHTMLElementFromSelectionNode implementation

- README.md
The previous link would direct to https://github.com/gocolly/colly/blob/master/graphs/contributors instead of the correct URL https://github.com/gocolly/colly/graphs/contributors.
> Fixed Contributors URL

- _examples/random_delay/random_delay.go
- http_backend.go
Added random delay config to limitRule that allow user to specify additional parameter to
randomized the delay on each request.
Testing Methodogy:
Used the rate_limit app in the _example dir and verify that adding RandomDelay will cause
each request to have different delay time.
> Added random delay per issue #54

- http_backend.go
If create returns error, file will be nil so panics. Defer moved after error check.
> [fix] close file after checking error in http backend

- http_backend.go
Using CacheDir on Windows fails on the first visit and closes the scraper.
The cache file must be closed before os.Rename is called or it will cause the error "The process cannot access the file because it is being used by another process" on Windows.
Rather than defer, we close the file intentionally after gob.Encode ensuring it is closed before os.Rename is called.
> cacheDir Windows Bug

- _examples/reddit/reddit.go
This pull request introduces an example for calling reddit.com/r/programming
This code has some interesting features.  
- It does some random time delaying
- Limits the parallelism
- Creates a generic struct to store crawl information
- Returns a mass splice with all stored crawl information at end of crawl
- Hits up the next page element to crawl the next page (if there are more) for more information!
I would appreciate if this example was introduced into the code-base!
If there are any critiques or changes needed to get it in please let me know!
> Introduces reddit example

- colly.go
- colly_test.go
I've added an explicit check for the error from the GET request and a simple test case for it.
Previously, the code ignored the error returned from the GET request. `resp` would then be `nil` in which case `robotstxt.FromResponse(resp)` returns `(nil,nil)` which would cause the runtime error a bit later in `robot.FindGroup(c.UserAgent)`.
> Connection error when getting robots.txt leads to runtime error

- colly.go
- colly_test.go
Now it is possible to define some regexp to blacklist some URL patterns.
For example:
```
package main
import (
"github.com/OSPG/colly"
"log"
"regexp"
)
func main() {
r := regexp.MustCompile(`https://.*debian\.org/?.*`)
r2 := regexp.MustCompile(`(png|jpg|jpeg|gif|ico|pdf|iso)$`)
c := colly.NewCollector(
colly.URLFilters(r),
colly.DisallowedURLFilters(r2),
)
c.OnHTML("a", func(e *colly.HTMLElement) {
link := e.Request.AbsoluteURL(e.Attr("href"))
if len(link) > 0 {
//		    log.Println("I'm going to try to visit", link)
c.Visit(link)
}
})
c.OnRequest(func(r *colly.Request) {
log.Println("visiting", r.URL.String())
})
log.Println(c.DisallowedURLFilters)
c.Visit("https://debian.org")
}
```
It will not visit any that matches with `(png|jpg|jpeg|gif|ico|pdf|iso)$`
> Add support to URL regexp blacklisting

- htmlelement.go
ForEach iterates over the elements matched by the first argument and calls the callback function on every HTMLElement match.
It is identical to ForEach except that it is possible to break out of the loop by returning false in the callback function. It returns the current Selection object.
> Add ForEachWithBreak function to HTMLElement

- _examples/local_files/html/child_page/one.html
- _examples/local_files/html/child_page/three.html
- _examples/local_files/html/child_page/two.html
- _examples/local_files/html/index.html
- _examples/local_files/local_files.go
- http_backend.go
This adds and example for how to use colly to visit local files.
In order for this to work, a slight change was needed to the
`http_backend` to prevent panics when an `http.Response` does not
include the original request, which appears to be the case for the
`FileTransport`.
To run this example, you must run the actual binary and not use
`go run` as the relative paths to the files will be different.
> Added local files example

- colly.go
- http_backend.go
- request.go
1. add feather: read gzipped HTTP response
2. fix: request marshal and unMarshal include headers (fix #169 )
> Read gzipped response and request marshal include headers

- unmarshal.go
- unmarshal_test.go
This commit adds support for unmarshalling values that are slices
of pointers (`[]*SomeStruct`) as first reported in #197.  This does
not include slices of structs (`[]SomeStruct`).
> Support umarshalling slices of pointers

- colly.go
The convention for Google App Engine applications is to pass around a `context.Context` rather than an `*http.Request`. Typically you pass context.Context around your application and use it to call various GAE services. This update means you can call Colly deep in your code somewhere where you only have `context.Context` available as you'd typically only have `*http.Request` available near the ingress point.
I have confirmed these changes work in a fork I am using on a live GAE app.
> update `Collector.Appengine` to take a `context.Context` rather than an `*http.Request`

- unmarshal.go
- unmarshal_test.go
This commit continues the work done in #205 by adding support for slices of structs.
Closes #197
> Add support for struct slices

- colly.go
Before visiting the URL, it's need to verify the resource by sending a HEAD request, otherwise the processing of the resource is interrupted without any notification.
> Check URL availability before visiting

- colly.go
Go handles setting a custom HTTP Host header in kind of a strange way. Instead of adding it to the `Headers` portion of a request, you have to set the `Host` field on the `Request` object itself (https://github.com/golang/go/issues/7682). Instead of trying to duplicate that approach, make it so that `Collector.scrape` will just copy any Host header from the given headers and set the `Host` on req.
> if the Host header is set, then set the Host field on http.Request

- unmarshal.go
- unmarshal_test.go
Per the request I had previously where I needed to have a generic struct and then use a map to unmarshal the required attributes.
Issue in question : https://github.com/gocolly/colly/issues/273
> Add map un-marshaling 

- colly.go
- colly_test.go
Using URL.Hostname() instead of URL.Host when calling Collector.isDomainAllowed.
Because the value of URL.Host contains Port number, we should trim it.
> [fix] using URL.Hostname() instead of URL.Host 

- colly.go
- http_backend.go
This pull request is mostly inspired by past issues I've had with leveraging sitemap files that have odd content encodings when using scrapy: https://github.com/scrapy/scrapy/blob/094dde6fdb1b03351888e437828af5da03f46352/scrapy/spiders/sitemap.py#L67
As per the above linked scrapy handling, some "child" sitemaps are gzipped but the content-encoding is not being set correctly. Instead the `Content-Type` is set to `application/x-gzip`.
Decompress the content as well as handle `.xml` or `.xml.gz` filenames.
> Tweaks to how xml sitemaps that are decompressed and handled

- colly.go
- http_backend.go
When checking robots.txt. The method uses the httpBackend.Client
directly and does not close the response body after usage.
The call to defer res.Body.Close() in httpBackend.Do() was too late to
close the response body after erroring on gzipped compressed bodies.
> Fix memory leaks via not closing http.Response.Body.

- response.go
Some MIME types do not involve any text data and should not be processed
in fixCharset.  This should be done instead of forcing the user to
toggle the Collector.DetectCharset flag as it could prove problematic.
Fix #312
> Ignore certain MIME types in fixCharset

- colly.go
The current checkRedirectFunc() copies the headers from the previous locations.  This leads to copying old cookies and possibly other stale information.  The golang default http.Client already copies the necessary headers to build the next request during a redirect before it reaches this code.  Fix for #294
> Remove code that copies headers on redirect

- colly.go
- proxy/proxy.go
```golang
rp, err := proxy.RoundRobinProxySwitcher()
if err != nil {
log.Fatal(err)
}
```
Code like this will cause a runtime error ,
try to fix this.
> Fix runtime error when proxy is empty

- colly.go
Running scrape on a protocol-less url like "go-colly.org" gives a
confusing error message:
```
Error: 0 - Get http://go-colly.org: http: no Host in request URL
```
Here is the code used to create this example:
```golang
package main
import (
"fmt"
"github.com/gocolly/colly"
)
func main() {
c := colly.NewCollector()
c.OnError(func(r *colly.Response, err error) {
fmt.Printf("Error: %d - %s \n", r.StatusCode, err)
})
c.Visit("go-colly.org")
}
```
The problem is that we added default "http://" Scheme after failing to
parse the "host" out of the URL, but the fact that we don't have a host
means that we won't be able to lookup the url, even after adding the
the "http" to the parsedURL struct.
With this patch, we generate an error that points directly at the issue:
```
Error: 0 - Get …
```
> remove Scheme default for better error message

- debug/webdebugger.go
When adding a large amount of links it can occur that the ConcurrentRequests map is being written and read at the same time, this fixes it with a Mutex.
> Fix concurrent WebDebugger map read/write

- colly.go
This does not change the API, but makes the generated documentation nicer to read by grouping all the collector options together.
> Factor out CollectorOption type

- colly.go
Fix `MAX_DEPTH` variable assignment on the envMap
> Fix MAX_DEPTH variable assignment

- htmlelement.go
While ChildText at htmlelement concatenates all text from the matching elements, ChildTexts returns the stripped text content of all the matching elements (non-concatenated) in a []string.
Can this be achieved with ChildAttrs? I think even if it is possible, it is shorter and more intuitive to have a ChildTexts method (specially for people like me that are not well acquainted with the query selectors).
> added ChildTexts method to htmlelement

- colly.go
- colly_test.go
- http_trace.go
- http_trace_test.go
- response.go
Go HTTP supports tracing with the "net/http/httptrace" package. This adds a very
basic HTTPTrace object to the HTTP Request that tracks HTTP request timing. **This
is useful for users wanting to tune their crawling based on RTT.**
The resulting trace object is added to the colly Response which is accessible
to a caller via any of the Response callbacks.
Commit includes unit tests for the new HTTPTrace object as well as a new case for colly_test.
> Adds HTTP Tracing to colly requests

- go.sum
- queue/queue.go
I found that a scraping run finished even though there were items still in the queue. It needed to be restarted to get the newer items from the first run.
This PR removes the locks and uses a channel instead. It seems to be working well on a long crawl (4+ days) with no need to restart.
> Queue improvements

- queue/queue.go
- queue/queue_test.go
The existing queue implementation has three drawbacks:
1. Infinite loop (#450)
2. Data race (#449)
3. Last requests may not be executed because of wrong implementation.
The third is a subtle bug. You can see the bug by `go test -v -timeout 10s ./queue` (be sure to checkout master branch and cherry-pick the test commit). The bug might not be shown as the bug is undeterministic.
This pull request addresses the three drawbacks.
I assumes that Storage stored in Queue must not be used by a user while Queue.Run() is running. The assumption can be considered a breaking change to some users. Be careful to merge.
> Fix Queue bug

- colly.go
- queue/queue.go
Instead of silently failing when adding a request to the queue return an error.
> Queue full error

- http_backend.go
Addresses https://github.com/gocolly/colly/issues/463 by reading the `URL.Path` from the `request` instance.
> fix reading URL.Path from request bug

- colly.go
- colly_test.go
Same request check implemented only GET requests in #77b8884. But  same post bodies also need to be checked and prevent duplicate post requests. Otherwise there is no way to prevent POST requests.
> Revisit detection improvement

- colly.go
- colly_test.go
The base itself can be relative, this is documented[1], and rarely
happens on the websites in the wild.
[1] https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base
> Fix relative <base> URL

- colly.go
- colly_test.go
- http_backend.go
When `OnResponse` callback is called, the request URL is updated to reflect the redirect that has been followed (if any).
Do the same for `OnResponseHeaders`, for consistency.
> Fix handling of redirected URLs in OnResponseHeaders

- colly.go
Hey!
I think `SetProxyFunc()` could simply override `DisableKeepAlives` and set it `true` as the default value. Otherwise, it will rotate proxies only on failed requests.
Also, you can reproduce this issue exactly with the example http://go-colly.org/docs/examples/proxy_switcher/
This PR addresses the issue #339
> SetProxyFunc: fix proxies rotation

- colly.go
- colly_test.go
When using non-nil `hdr` parameter with `c.Request` method, and not setting User-Agent header explicitly, it would be left unset (when it should've been set to `c.UserAgent`). This means that Go HTTP client would use the default "Go-http-client/2.0" string.
Suppressing the header altogether is still possible by setting it to empty string.
> Fix default User-Agent when using custom headers

- http_backend.go
The checkHeadersFunc is called before response cached body, it can check cache expire or force cache invalidation.
```
c.OnResponseHeaders(func(r *colly.Response) {
respTime, err := time.Parse(http.TimeFormat, r.Headers.Get("Date"))
if err != nil || time.Now().UTC().Sub(respTime) > maxAge {
r.StatusCode = 510 // invalidate the cache
}
})
```
> Add httpBackend cache response callback

- extensions/random_user_agent.go
- Removed Firefox version earlier than 2020
- Removed Google Chrome version earlier than 2020
- Added support for Microsoft Edge
- Updated Mac OS version strings (10.13.x ~ 12.2.x)
- Extended support for Android 10/11
- Fixed incorrect OS version string for Windows 10
> Update User-Agent strings for Desktop

- colly.go
- colly_test.go
- go.mod
- go.sum
- queue/queue.go
- request.go
Although the library has zero popularity, its test suite is extensive (borrowed from WHATWG URL repo, actually), and in my tests, it does solve the problems without adding new regressions.
See #596
> Use github.com/nlnwa/whatwg-url for URL parsing

- cmd/colly/colly.go
OnRequest/OnResponse/OnError these three callbacks don't has element-selectors arg, so remove
> fix: generated code has compile error

- colly.go
- colly_test.go
- queue/queue.go
- request.go
Go `net/http` cannot send HTTP requests containing invalid URL encoding in path (e.g. bare percent)
at all[1]. Browsers send a bare percent in such scenario, and do not implicitly autoencode it.
Until the upstream issue is resolved somehow, we have only two alternatives: either fail to fetch such URLs, or at least attempt the autoencoded variant. Lots of webservers handle them the same way, so it's worth trying.
There aren't too many websites with invalid URL encoding in path component, though.
[1] https://github.com/golang/go/issues/29808
> Work around invalid URL encoding in path

- colly.go
- colly_test.go
- request.go
Fixes #564
This PR adds support for passing in custom HTTP headers for the crawler to use, and overriding the `Host` HTTP header. This can be useful when attempting to crawl an IP address while targeting a specific virtual host used in the web server on that IP address.
> Host & Custom Header Support

- .github/ISSUE_TEMPLATE.md
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.md
Add some simple templates for bug report/feature requests, and, more importantly, nudge questions to Stack Overflow.
How it looks like: https://github.com/WGH-/colly/issues/new/choose
> Add GitHub issue templates and nudge questions to Stack Overflow

- colly.go
- colly_test.go
This commit introduces a breaking change: `ErrAlreadyVisited` is replaced
with `AlreadyVisitedError`, which allows the user to know the redirect
destination, which might not match the URL passed to `Visit` when multiple
redirects are followed.
See #405
Currently draft because it's based on code cleanup made in #678
> Fix redirects ignoring AllowURLRevisit=false 

- colly.go
- colly_test.go
Signed-off-by: Guilhem Lettron <guilhem@barpilot.io>
> feat: Add MaxRequests paramete

- .github/workflows/ci.yml
- colly.go
- extensions/random_user_agent.go
- http_backend.go
- unmarshal.go
Upstream supports 1.19 and 1.18 right now, but let's be generous and also include 1.17.
This should fix CI, since Colly can't be built properly on 1.15 and older, and it has been this way for a while.
Also enable CI runs for pull requests, as it's good to know whether they're ok or not, and GitHub Actions are free anyway.
> Update CI configuration

- go.mod
- go.sum
The new Cascadia version includes:
- Case-insensitive CSS selectors attributes with `i`(https://github.com/andybalholm/cascadia/pull/51)
- Support of a lot of pseudo-classes (https://github.com/andybalholm/cascadia/issues/50)
Goquery has recently upgraded Cascadia too.
> upgrade Cascadia version

- extensions/random_user_agent.go
- Removed Firefox version earlier than Jun 1, 2022
- Removed Google Chrome version earlier than Jun 1, 2022
- Removed Microsoft Edge version earlier than Jun 1, 2022
- Removed Opera version earlier than Jan 1, 2023
- Updated Mac OS version strings (10.2.x ~ 13.3.x)
- Extended support for Android 12/13
- Updated build code for Nexus 10
- Remove legacy devices support
- Add support for Pixel 7
- Add support for Pixel 6
- Add support for Pixel 5
- Add support for Pixel 4
Fixes: #762
> Update User-Agent strings for 2023

- colly.go
- colly_test.go
> put accept header before OnRequest

- colly.go
- colly_test.go
- request.go
when retry scrape
requestData will loss in http.NewRequest
so Seek requestData before scrape.NewRequest
```
req.ContentLength  always 0 and
if req.GetBody != nil && req.ContentLength == 0 {
req.Body = NoBody
req.GetBody = func() (io.ReadCloser, error) { return NoBody, nil }
}
```
> Fix Bug: retry scrape will lost POST requestData

- colly.go
- colly_test.go
Web pages can be served without `Content-Type` set, in which case browsers employ content sniffing. Do the same here, in Colly.
While we're at it, change the Content-Type check to something stricter than mere "html" substring match.
> Implement content sniffing for HTML parsing

- colly.go
In my project, I have `OnHTML` and `OnXML` callbacks, and I got confused when I read in the documentation that `OnScraped` would be executed after `OnHTML`. To figure out what would happen with `OnXML`, I had to dive into the source code.
This PR makes the `OnScraped` description a little clearer.
> doc: mention that OnScraped executes after OnHTML and OnXML

- .vscode/launch.json
- colly.go
- colly_test.go
I've added a fix for the issue #835 of calling `html` and `xml` detaches while inside a `html` or `xml` callback. Previously this caused the slice to be modified while iterating over it, which might cause other callbacks to be skipped or to be executed twice (see [this playground](https://go.dev/play/p/5MDOu-Eo5LQ) for a short demo of a bug when modifying a slice while ranging over it). 
This PR changes the callback execution logic to introduce a parameter `active` and track which callbacks have `active == true` and only execute those. Calling a detach will set `active` to `false` for the callback, at a later step we remove all inactive callbacks.
This PR also adds a test for this issue.
> fix #835: calling a callback detach while executing a callback might cause callbacks to be skipped or executed twice

- colly.go
The comment above Collector.SetProxyFunc said it only overrides the transport
if it “is not http.RoundTripper”, but the code actually looks for *http.Transport.
This PR updates the comment to correctly state that we override when the
existing Transport is not of type *http.Transport.
- Keeps documentation in sync with implementation.
- Avoids confusion for future contributors reading the code.
This is purely a comment change; no behavior is affected.
> docs: correct comment in SetProxyFunc to refer to *http.Transport

- _examples/coursera_courses/coursera_courses.go
- colly.go
- colly_test.go
- http_backend.go
Resolves #834.
This pull request adds support for a new CacheExpiration option to the Collector struct, allowing users to set a duration after which cached responses are considered stale and will be refreshed.
> Add cache expiration option

- _examples/instagram/instagram.go
An extra colon in the JSON tag can cause parsing errors.
> fix: Fix incorrect JSON tag
